/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as catalogIndexRouteImport } from './routes/(catalog)/index'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin'
import { Route as ProductIdIndexRouteImport } from './routes/product.$id/index'
import { Route as AuthPaymentIndexRouteImport } from './routes/_auth.payment/index'
import { Route as AuthOrdersIndexRouteImport } from './routes/_auth.orders/index'
import { Route as AuthCartIndexRouteImport } from './routes/_auth.cart/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth.admin/index'
import { Route as AuthPaymentSuccessIndexRouteImport } from './routes/_auth.payment.success/index'
import { Route as AuthOrdersIdIndexRouteImport } from './routes/_auth.orders.$id/index'
import { Route as AuthAdminUsersIndexRouteImport } from './routes/_auth.admin.users/index'
import { Route as AuthAdminProductsIndexRouteImport } from './routes/_auth.admin.products/index'
import { Route as AuthAdminOrdersIndexRouteImport } from './routes/_auth.admin.orders/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const catalogIndexRoute = catalogIndexRouteImport.update({
  id: '/(catalog)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const ProductIdIndexRoute = ProductIdIndexRouteImport.update({
  id: '/product/$id/',
  path: '/product/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPaymentIndexRoute = AuthPaymentIndexRouteImport.update({
  id: '/payment/',
  path: '/payment/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersIndexRoute = AuthOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCartIndexRoute = AuthCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthPaymentSuccessIndexRoute = AuthPaymentSuccessIndexRouteImport.update({
  id: '/payment/success/',
  path: '/payment/success/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersIdIndexRoute = AuthOrdersIdIndexRouteImport.update({
  id: '/orders/$id/',
  path: '/orders/$id/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersIndexRoute = AuthAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminProductsIndexRoute = AuthAdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminOrdersIndexRoute = AuthAdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof catalogIndexRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/cart/': typeof AuthCartIndexRoute
  '/orders/': typeof AuthOrdersIndexRoute
  '/payment/': typeof AuthPaymentIndexRoute
  '/product/$id/': typeof ProductIdIndexRoute
  '/admin/orders/': typeof AuthAdminOrdersIndexRoute
  '/admin/products/': typeof AuthAdminProductsIndexRoute
  '/admin/users/': typeof AuthAdminUsersIndexRoute
  '/orders/$id/': typeof AuthOrdersIdIndexRoute
  '/payment/success/': typeof AuthPaymentSuccessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof catalogIndexRoute
  '/login': typeof LoginIndexRoute
  '/admin': typeof AuthAdminIndexRoute
  '/cart': typeof AuthCartIndexRoute
  '/orders': typeof AuthOrdersIndexRoute
  '/payment': typeof AuthPaymentIndexRoute
  '/product/$id': typeof ProductIdIndexRoute
  '/admin/orders': typeof AuthAdminOrdersIndexRoute
  '/admin/products': typeof AuthAdminProductsIndexRoute
  '/admin/users': typeof AuthAdminUsersIndexRoute
  '/orders/$id': typeof AuthOrdersIdIndexRoute
  '/payment/success': typeof AuthPaymentSuccessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/(catalog)/': typeof catalogIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/cart/': typeof AuthCartIndexRoute
  '/_auth/orders/': typeof AuthOrdersIndexRoute
  '/_auth/payment/': typeof AuthPaymentIndexRoute
  '/product/$id/': typeof ProductIdIndexRoute
  '/_auth/admin/orders/': typeof AuthAdminOrdersIndexRoute
  '/_auth/admin/products/': typeof AuthAdminProductsIndexRoute
  '/_auth/admin/users/': typeof AuthAdminUsersIndexRoute
  '/_auth/orders/$id/': typeof AuthOrdersIdIndexRoute
  '/_auth/payment/success/': typeof AuthPaymentSuccessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login/'
    | '/admin/'
    | '/cart/'
    | '/orders/'
    | '/payment/'
    | '/product/$id/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/users/'
    | '/orders/$id/'
    | '/payment/success/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/cart'
    | '/orders'
    | '/payment'
    | '/product/$id'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/orders/$id'
    | '/payment/success'
  id:
    | '__root__'
    | '/_auth'
    | '/_auth/admin'
    | '/(catalog)/'
    | '/login/'
    | '/_auth/admin/'
    | '/_auth/cart/'
    | '/_auth/orders/'
    | '/_auth/payment/'
    | '/product/$id/'
    | '/_auth/admin/orders/'
    | '/_auth/admin/products/'
    | '/_auth/admin/users/'
    | '/_auth/orders/$id/'
    | '/_auth/payment/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  catalogIndexRoute: typeof catalogIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProductIdIndexRoute: typeof ProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(catalog)/': {
      id: '/(catalog)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof catalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/product/$id/': {
      id: '/product/$id/'
      path: '/product/$id'
      fullPath: '/product/$id/'
      preLoaderRoute: typeof ProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/payment/': {
      id: '/_auth/payment/'
      path: '/payment'
      fullPath: '/payment/'
      preLoaderRoute: typeof AuthPaymentIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/': {
      id: '/_auth/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthOrdersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cart/': {
      id: '/_auth/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof AuthCartIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/payment/success/': {
      id: '/_auth/payment/success/'
      path: '/payment/success'
      fullPath: '/payment/success/'
      preLoaderRoute: typeof AuthPaymentSuccessIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders/$id/': {
      id: '/_auth/orders/$id/'
      path: '/orders/$id'
      fullPath: '/orders/$id/'
      preLoaderRoute: typeof AuthOrdersIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users/': {
      id: '/_auth/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthAdminUsersIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/products/': {
      id: '/_auth/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthAdminProductsIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/orders/': {
      id: '/_auth/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AuthAdminOrdersIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthAdminOrdersIndexRoute: typeof AuthAdminOrdersIndexRoute
  AuthAdminProductsIndexRoute: typeof AuthAdminProductsIndexRoute
  AuthAdminUsersIndexRoute: typeof AuthAdminUsersIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthAdminOrdersIndexRoute: AuthAdminOrdersIndexRoute,
  AuthAdminProductsIndexRoute: AuthAdminProductsIndexRoute,
  AuthAdminUsersIndexRoute: AuthAdminUsersIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthCartIndexRoute: typeof AuthCartIndexRoute
  AuthOrdersIndexRoute: typeof AuthOrdersIndexRoute
  AuthPaymentIndexRoute: typeof AuthPaymentIndexRoute
  AuthOrdersIdIndexRoute: typeof AuthOrdersIdIndexRoute
  AuthPaymentSuccessIndexRoute: typeof AuthPaymentSuccessIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthCartIndexRoute: AuthCartIndexRoute,
  AuthOrdersIndexRoute: AuthOrdersIndexRoute,
  AuthPaymentIndexRoute: AuthPaymentIndexRoute,
  AuthOrdersIdIndexRoute: AuthOrdersIdIndexRoute,
  AuthPaymentSuccessIndexRoute: AuthPaymentSuccessIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  catalogIndexRoute: catalogIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProductIdIndexRoute: ProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
